# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LojYbzV-CB7h1FMhmtOffc_QQJ-yBQnx
"""

def load_terrain():
    """
    Returns the terrain data as a 9x9 matrix.
    Each 1 represents light on, and each 0 represents light off.
    """
    terrain = [
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
    ]
    return terrain

if __name__ == "__main__":
    # Example usage
    terrain = load_terrain()
    for row in terrain:
        print(row)